### PR TITLE
Updated hashing passwords

### PR DESCRIPTION
**Pull request by armanon**
Adding hashing for passwords to update

### CODE REVIEW

**Comment by briannguyen11** [comment]
Might have to double check before pushing to main.

**Comment by ejendret** [comment]
Will try to check over later

**Comment by ejendret** [comment]
Not super sure why it's trying to add stuff instead of modify, unless it's comparing to the arman remote branch instead of main. I only checked over the backend but most of it seems fine.

**Comment by ejendret** [comment]
Potential issue is that file names have changed. tasks-services vs task-services. Should be able to integrate backend stuff manually but there might be a better way with git.

**Comment by 00qnavry00** [comment]
Isn't the MyApp.js / App.js an older version?

**Comment by ejendret** [comment]
Going to close this for now, we can reopen it later

**Pull request closed without merging**
